version: 2.1
orbs:
  hello-command: yutagoto/hello-world@0.0.1

jobs:
  build:
    docker:
    - image: bash
    steps:
    - run: "echo 'testing building...'"
    - hello-command/hello:
        username: ".Gotch"

workflows:
  main:
    jobs:
    - build
